# TensorFlow 2.0

-----

TensorFlow is an open-source library used to train and develop machine learning models. More specifically, it is a symbolic math library. TensorFlow is an end-to-end platform that caters to beginners and experts alike. TensorFlow is not only flexible but also offers multiple layers of abstraction. Its APIs operate at both high and low levels. Because TensorFlow is created by the Google Brain team, there is both documentation and training support.

TensorFlow is used to create data flow graphs. This is a structure in which data moves through a graph that processes at each node. These nodes are mathematical operations, and the connections represent a tensor or a multidimensional data array. These operations are where learning occurs, which can train neural networks for machine learning, natural language processing, or even partial differential equation-based simulations. These neural networks can be used for image recognition, word embeddings, recurrent neural networks, handwritten digit classification, or sequence-to-sequence models. The mathematical operations that occur do not happen within Python. Instead, they occur in C++ where they are written in powerful and high-performance binaries. Python is only the programming abstraction that links everything together. Because it is in Python, it makes it easier for developers to learn. With that said, TensorFlow can still be difficult for beginners to learn due to the complexity of the content. Here is my attempt to create a mini tutotrial to understand the basics of TensorFlow.

Import packages

In [1]:
import os
import numpy as np
import tensorflow as tf

Check tensorflow version

In [2]:
tf.__version__

'2.6.0'

## What is TensorFlow?

TensorFlow is an open-source end-to-end platform for creating Machine Learning applications. It is a symbolic math library that uses dataflow and differentiable programming to perform various tasks focused on training and inference of deep neural networks.

## How TensorFlow Works
TensorFlow enables you to build dataflow graphs and structures to define how data moves through a graph by taking inputs as a multi-dimensional array called **Tensor**. It allows you to construct a flowchart of operations that can be performed on these inputs, which goes at one end and comes at the other end as output.

## Tensor

In TensorFlow, a tensor is a collection of feature vectors (i.e., array) of n-dimensions. For instance, if we have a 2x3 matrix with values from 1 to 6, we write:



\begin{bmatrix}
    1 & 2 & 3 \\
    4 & 5 & 6
  \end{bmatrix}
  
TensorFlow represents this matrix as

[[1, 2, 3],
   [4, 5, 6]]
   
## Types of Tensor
In TensorFlow, all the computations pass through one or more tensors. A tf.tensor is an object with three properties:

- A unique label (name)
- A dimension (shape)
- A data type (dtype)

Each operation you will do with TensorFlow involves the manipulation of a tensor. There are two main tensor types:

- tf.Variable
- tf.constant

### Constant
Creating constant tensors i.e. their values cant change.

- can be used to create bais in image processing
- can be used to constant matrices

In [3]:
# Tensor with string values
hello = tf.constant('Hello TensorFlow!!')
print (f'{hello}\n',hello)
print (hello.numpy())


b'Hello TensorFlow!!'
 tf.Tensor(b'Hello TensorFlow!!', shape=(), dtype=string)
b'Hello TensorFlow!!'


In [4]:
# Tensor with integer values
num = tf.constant(1)
print(num)
print(f'{num}')

tf.Tensor(1, shape=(), dtype=int32)
1


In [5]:
# Tensor with decimal values
decimal = tf.constant(1.12345, tf.float32)
print(decimal)

tf.Tensor(1.12345, shape=(), dtype=float32)


In [6]:
# Tensor of dimension 1
r1_vector = tf.constant([1,3,5], tf.int16)
print(r1_vector)
r2_boolean = tf.constant([True, True, False], tf.bool)
print(r2_boolean)

# Tensor of dimension 2
r2_matrix = tf.constant([ [1, 2],
                          [3, 4] ],tf.int32)
print(r2_matrix)

# Tensor of dimension 3
r3_matrix = tf.constant([ [[1, 2],
                           [3, 4], 
                           [5, 6]] ], tf.int16)
print(r3_matrix)

tf.Tensor([1 3 5], shape=(3,), dtype=int16)
tf.Tensor([ True  True False], shape=(3,), dtype=bool)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[[1 2]
  [3 4]
  [5 6]]], shape=(1, 3, 2), dtype=int16)


In [7]:
D = tf.constant(50,shape=(6,2))
print (D)

tf.Tensor(
[[50 50]
 [50 50]
 [50 50]
 [50 50]
 [50 50]
 [50 50]], shape=(6, 2), dtype=int32)


### Variable
To create a variable, you can use tf.Variable() method

- all the weights in neural network are defined as variables

In [8]:
A = tf.Variable(initial_value = ([[0,1,2,3],[5,6,7,8]]))
print (A.numpy())
#shape of the variable
print (A.shape)
#dimension of a matrix
print (tf.rank(A))

[[0 1 2 3]
 [5 6 7 8]]
(2, 4)
tf.Tensor(2, shape=(), dtype=int32)


In [9]:
b = tf.Variable([[1],[2],[3],[4]])
print (b.shape)
print (tf.rank(b))

(4, 1)
tf.Tensor(2, shape=(), dtype=int32)


**Using Eager Execution**

With eager execution ([relased](!https://ai.googleblog.com/2017/10/eager-execution-imperative-define-by.html) in late 2017), TensorFlow's eager execution is an imperative programming environment that evaluates operations immediately, without building graphs: operations return concrete values instead of constructing a computational graph to run later. This makes it easy to get started with TensorFlow and debug models, and it reduces boilerplate as well. Operations execute immediately and return their values to Python without requiring a Session.run(). For example, to multiply two matrices together, we write this:

In [10]:
w = tf.Variable([.5],tf.float32)
b = tf.Variable([-.5],tf.float32)

x = tf.Variable([5.0],tf.float32)
y=w*x +b
print('w:',w)
print('b:',b)
print('x:',x)
print('y:',y)

w: <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.5], dtype=float32)>
b: <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-0.5], dtype=float32)>
x: <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([5.], dtype=float32)>
y: tf.Tensor([2.], shape=(1,), dtype=float32)


In [11]:
y.numpy()

array([2.], dtype=float32)

## Creating tensors from Existing Objects

In [12]:
t = tf.convert_to_tensor(9, dtype=tf.float64)
t

<tf.Tensor: shape=(), dtype=float64, numpy=9.0>

**Creating tensors from an array**

In [13]:
one_dim_array = ([1], [2], [3], [4], [5])
print("one_dim_array Shape : ", one_dim_array)

tf_t = tf.convert_to_tensor(one_dim_array, dtype=tf.float64)
print('\n')
print(tf_t)
print('rank of tf_t : ', tf.rank(tf_t))     #Note: if we do not use tfs.run(), the tf.rank will only describe the node
print('shape of tf_t: ', tf.shape(tf_t))
print('\n')
print('tf_t[0] : ', tf_t[0])
print('tf_t[2] : ', tf_t[2])
print('\n')
print('run(tf_t) : \n', tf_t)

one_dim_array Shape :  ([1], [2], [3], [4], [5])


tf.Tensor(
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]], shape=(5, 1), dtype=float64)
rank of tf_t :  tf.Tensor(2, shape=(), dtype=int32)
shape of tf_t:  tf.Tensor([5 1], shape=(2,), dtype=int32)


tf_t[0] :  tf.Tensor([1.], shape=(1,), dtype=float64)
tf_t[2] :  tf.Tensor([3.], shape=(1,), dtype=float64)


run(tf_t) : 
 tf.Tensor(
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]], shape=(5, 1), dtype=float64)


## Creating tensors with tf.zeros and tf.ones

In [14]:
# Making a tensor filled with zeros. shape=[rows, columns]
tensor = tf.zeros(shape=[3, 4], dtype=tf.int32)
print(('Tensor full of zeros as int32, 3 rows and 4 columns:\n{0}').format(
    tensor.numpy()
))

Tensor full of zeros as int32, 3 rows and 4 columns:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [15]:
# Making a tensor filled with zeros with data type of float32
tensor = tf.ones(shape=[5, 3], dtype=tf.float32)
print(('\nTensor full of ones as float32, 5 rows and 3 columns:\n{0}').format(
    tensor.numpy()
))


Tensor full of ones as float32, 5 rows and 3 columns:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Reshape data with tf.reshape

In [16]:
# Making a tensor for reshaping
tensor = tf.constant([[3, 2],
                      [5, 2],
                      [9, 5],
                      [1, 3]])

# Reshaping the tensor into a shape of: shape = [rows, columns]
reshaped_tensor = tf.reshape(tensor = tensor,
                             shape = [1, 8])

print(f'Tensor BEFORE reshape:\n{tensor.numpy()}')
print(f'Tensor AFTER reshape:\n{reshaped_tensor.numpy()}')

Tensor BEFORE reshape:
[[3 2]
 [5 2]
 [9 5]
 [1 3]]
Tensor AFTER reshape:
[[3 2 5 2 9 5 1 3]]


##  Cast tensors to other data types with tf.cast

In [17]:
# Making a tensor
t = tf.constant([[3.1, 2.8],
                      [5.2, 2.3],
                      [9.7, 5.5],
                      [1.1, 3.4]], 
                      dtype=tf.float32)
t_int = tf.cast(tensor, tf.int32)

print(f'Tensor with floats:\n{t.numpy()}')
print(f'Tensor cast from float to int :\n{t_int.numpy()}')

Tensor with floats:
[[3.1 2.8]
 [5.2 2.3]
 [9.7 5.5]
 [1.1 3.4]]
Tensor cast from float to int :
[[3 2]
 [5 2]
 [9 5]
 [1 3]]


## Linear Algebra Operations

1. Transponse tensor with `tf.transpose`
2. Matrix multiplication with `tf.matmul`
3. Element-wise multiplication with `tf.multiply`
4. Identity matrix with tf.eye
5. Determinant with tf.linalg.det
6. Dot product with tf.tensordot

### Transpose a tensor with tf.transpose

In [18]:
A = tf.constant([[3, 7],
                 [1, 9]])

A_T = tf.transpose(A)

print(f'The transposed matrix A:\n{A_T}')

The transposed matrix A:
[[3 1]
 [7 9]]


### Matrix multiplication with tf.matmul

In [19]:
# Some Matrix A
A = tf.constant([[3, 7],
                 [1, 9]])

# Some vector v
v = tf.constant([[5],
                 [2]])

# Matrix multiplication of A.v^T
Av = tf.matmul(A, v)

print(f'Matrix Multiplication of A and v results in a new Tensor:\n{Av}')

Matrix Multiplication of A and v results in a new Tensor:
[[29]
 [23]]


### Element-wise multiplication with tf.multiply

In [20]:
# Element-wise multiplication
Av = tf.multiply(A, v)
print(f'Element-wise multiplication of A and v results in a new Tensor:\n{Av}')

Element-wise multiplication of A and v results in a new Tensor:
[[15 35]
 [ 2 18]]


### Identity matrix with tf.eye

In [21]:
A = tf.constant([[3, 7],
                 [1, 9],
                 [2, 5]])

# Get number of dimensions
rows, columns = A.shape
print(f'Get rows and columns in tensor A:\n{rows} rows\n {columns} columns')

# Making identity matrix
A_identity = tf.eye(num_rows = rows,
                    num_columns = columns,
                    dtype = tf.int32)

print(f'\nThe identity matrix of A:\n{A_identity}')

# Making identity matrix
B_identity = tf.eye(num_rows = 3,
                    num_columns = 4,
                    dtype = tf.int32)

print(f'\nThe identity matrix B:\n{B_identity}')

Get rows and columns in tensor A:
3 rows
 2 columns

The identity matrix of A:
[[1 0]
 [0 1]
 [0 0]]

The identity matrix B:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


### Determinant with tf.linalg.det

In [22]:
# Reusing Matrix A
A = tf.constant([[3, 7],
                 [1, 9]])

# Determinant must be: half, float32, float64, complex64, complex128
# Thus, we cast A to the data type float32
A = tf.dtypes.cast(A, tf.float32)

# Finding the determinant of A
det_A = tf.linalg.det(A)

print(f'The determinant of A:\n{det_A}')

The determinant of A:
20.0


### Dot product with tf.tensordot

In [23]:
# Defining a 3x3 matrix
A = tf.constant([[32, 83, 5],
                 [17, 23, 10],
                 [75, 39, 52]])

# Defining another 3x3 matrix
B = tf.constant([[28, 57],
                 [91, 10],
                 [37, 13]])

# Finding the dot product
dot_AB = tf.tensordot(a=A, b=B, axes=1).numpy()

print(f'Dot product of A and B results in a new Tensor:\n{dot_AB}')

Dot product of A and B results in a new Tensor:
[[8634 2719]
 [2939 1329]
 [7573 5341]]


# Linear regression using TensorFlow

In [24]:
train_X = [3.3, 4.4, 5.5, 6.71, 6.93, 4.168, 9.779, 6.182, 7.59, 2.167,
           7.042, 10.791, 5.313, 7.997, 5.654, 9.27, 3.1]
train_Y = [1.7, 2.76, 2.09, 3.19, 1.694, 1.573, 3.366, 2.596, 2.53, 1.221,
           2.827, 3.465, 1.65, 2.904, 2.42, 2.94, 1.3]
NUM_EXAMPLES = len(train_X)


#create model paramters with initial values 
W = tf.Variable(0.)
b = tf.Variable(0.)

#training info
train_steps = 100
learning_rate = 0.01

for i in range(train_steps):
    #watch the gradient flow 
    with tf.GradientTape() as tape:
        
        #forward pass 
        yhat = train_X * W + b
        
        #calcuate the loss (difference squared error)
        error = yhat - train_Y
        loss = tf.reduce_mean(tf.square(error))
        
    #evalute the gradient with the respect to the paramters
    dW, db = tape.gradient(loss, [W, b])
    
    #update the paramters using Gradient Descent  
    W.assign_sub(dW * learning_rate)
    b.assign_sub(db* learning_rate)
    
    #print the loss every 20 iterations 
    if i % 20 == 0:
        print("Loss at step {:03d}: {:.3f}".format(i, loss))

print(f'W : {W.numpy()} , b  = {b.numpy()} ')

Loss at step 000: 6.100
Loss at step 020: 0.217
Loss at step 040: 0.211
Loss at step 060: 0.206
Loss at step 080: 0.201
W : 0.3344224691390991 , b  = 0.2118747979402542 


# Functions in TensorFlow 2.0

`tf.function` is a decorator function provided by Tensorflow 2.0 that converts regular python code to a callable Tensorflow graph function, which is usually more performant and python independent

In other words, `tf.function` constructs a callable that executes a TensorFlow graph (`tf.Graph`) created by trace-compiling the TensorFlow operations in `func`, effectively executing `func` as a TensorFlow graph.

In [25]:
@tf.function
def f(x,y):
    return x**2+y

x = tf.constant([2,3])
y = tf.constant([3,-2])

f(x,y)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 7], dtype=int32)>

TensorFlow Functions with `@tf.function` offer a significant speedup, because TensorFlow uses AutoGraph to convert functions to graphs, which in turn runs faster.

In [26]:
import timeit
conv_layer = tf.keras.layers.Conv2D(100, 3)

@tf.function
def conv_fn(image):
  return conv_layer(image)

image = tf.zeros([1, 200, 200, 100])
# warm up
conv_layer(image); conv_fn(image)

no_tf_fn = timeit.timeit(lambda: conv_layer(image), number=10)
with_tf_fn = timeit.timeit(lambda: conv_fn(image), number=10)
difference = no_tf_fn - with_tf_fn

print("Without tf.function: ", no_tf_fn)
print("With tf.function: ", with_tf_fn)
print("The difference: ", difference)


Without tf.function:  2.643772231000014
With tf.function:  2.201659479
The difference:  0.4421127520000141


# CPU vs GPU

In [27]:
import time

cpu_slot = 0
gpu_slot = 0

# Using CPU at slot 0
with tf.device('/CPU:' + str(cpu_slot)):
    # Starting a timer
    start = time.time()

    # Doing operations on CPU
    A = tf.constant([[3, 2], [5, 2]])
    print(tf.eye(2,2))

    # Printing how long it took with CPU
    end = time.time() - start
    print(end)

# Using the GPU at slot 0
with tf.device('/GPU:' + str(gpu_slot)):
    # Starting a timer
    start = time.time()

    # Doing operations on GPU
    A = tf.constant([[3, 2], [5, 2]])
    print(tf.eye(2,2))

    # Printing how long it took with GPU
    end = time.time() - start
    print(end)

tf.Tensor(
[[1. 0.]
 [0. 1.]], shape=(2, 2), dtype=float32)
0.0034093856811523438
tf.Tensor(
[[1. 0.]
 [0. 1.]], shape=(2, 2), dtype=float32)
0.002518892288208008


# Model subclassing using keras and tensorflow

## Load and prepare the MNIST data

In [30]:
from tensorflow.keras.layers import Dense, Flatten, Conv2D
from tensorflow.keras import Model
mnist = tf.keras.datasets.mnist

# Load mnist data and split into train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data(path=os.getcwd()+'/mnist.npz')
x_train, x_test = x_train / 255.0, x_test / 255.0

11501568/11490434 [==============================] - 0s 0us/step


In [31]:
# Check shape of data
print('MNIST Dataset Shape:')
print(f'x_train: {x_train.shape}')
print(f'y_train: {y_train.shape}')
print(f'x_test:  {x_test.shape}')
print(f'y_test:  {y_test.shape}')

MNIST Dataset Shape:
x_train: (60000, 28, 28)
y_train: (60000,)
x_test:  (10000, 28, 28)
y_test:  (10000,)


In [32]:
# Add a channels dimension
x_train = x_train[..., tf.newaxis].astype("float32")
x_test = x_test[..., tf.newaxis].astype("float32")

In [33]:
# Check shape of data
print('MNIST Dataset Shape:')
print(f'x_train: {x_train.shape}')
print(f'y_train: {y_train.shape}')
print(f'x_test:  {x_test.shape}')
print(f'y_test:  {y_test.shape}')

MNIST Dataset Shape:
x_train: (60000, 28, 28, 1)
y_train: (60000,)
x_test:  (10000, 28, 28, 1)
y_test:  (10000,)


Use tf.data to batch and shuffle the dataset:

In [34]:
train_ds = tf.data.Dataset.from_tensor_slices(
    (x_train, y_train)).shuffle(10000).batch(32)

test_ds = tf.data.Dataset.from_tensor_slices((x_test, y_test)).batch(32)

## Build the tf.keras model using the Keras model subclassing API:
- Create a subclass `MyModel` using keras `Model` class which groups layers into an object with training and inference features.

- The `super()` function is used to run the superclass (i.e.`Model`) of the current subclass. 

- The layers are defined in `__init__` as instance attributes and the model's forward pass is implemented in `call` function.

In [35]:
class MyModel(Model):
    def __init__(self):
        super().__init__()
        self.conv1 = Conv2D(32,2)
        self.flatten = Flatten()
        self.d1 = Dense(128,activation='relu')
        self.d2 = Dense(10)
        
    def call(self, x):
        x = self.conv1(x)
        x = self.flatten(x)
        x = self.d1(x)
        return self.d2(x)
    
# Create an instance of the model
model = MyModel()
        

Choose an optimizer and loss function for training:

In [36]:
loss_object = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
optimizer = tf.keras.optimizers.Adam()

In [37]:
train_loss = tf.keras.metrics.Mean(name='train_loss')
train_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(name='train_accuracy')

test_loss = tf.keras.metrics.Mean(name='test_loss')
test_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(name='test_accuracy')

## Train the model
In the next step:

- annotate the function with @tf.function for as much of a speedup as possible. 
- the `tf.GradientTape()` records gradients onto a variable tape, which we can access afterwards
- make predictions using `model` object
- call the object holding the loss function with the labels and predictions
- get the gradient from the gradient tape and apply them using the update rule from the optimizer picked

In [38]:
@tf.function
def train_step(images, labels):
    with tf.GradientTape() as tape:
        # training=True is only needed if there are layers with different
        # behavior during training versus inference (e.g. Dropout).
        predictions = model(images, training=True)
        loss = loss_object(labels, predictions)
    gradients = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))
    
    train_loss(loss)
    train_accuracy(labels, predictions)

## Test the model

The next function is just a test step, used to test the last training step. This function is almost identical to the`train_step` function, except there are no gradients and updates.

In [39]:
@tf.function
def test_step(images, labels):
    # training=False is only needed if there are layers with different
    # behavior during training versus inference (e.g. Dropout).
    predictions = model(images, training=False)
    t_loss = loss_object(labels, predictions)
    
    test_loss(t_loss)
    test_accuracy(labels, predictions)

The next step ties all the previous steps together and trains and tests the network for the number of epochs defined.

In [40]:
EPOCHS = 5

for epoch in range(EPOCHS):
    # Reset the metrics at the start of the next epoch
    train_loss.reset_states()
    train_accuracy.reset_states()
    test_loss.reset_states()
    test_accuracy.reset_states()
    
    for images, labels in train_ds:
        train_step(images, labels)
    print(
        f'Epoch {epoch + 1}, '
        f'Loss: {train_loss.result()}, '
        f'Accuracy: {train_accuracy.result() * 100}')

Epoch 1, Loss: 0.21552862226963043, Accuracy: 93.56666564941406
Epoch 2, Loss: 0.09783831983804703, Accuracy: 96.95500183105469
Epoch 3, Loss: 0.06611628830432892, Accuracy: 97.84667205810547
Epoch 4, Loss: 0.048738982528448105, Accuracy: 98.42166900634766
Epoch 5, Loss: 0.036590006202459335, Accuracy: 98.79833221435547
